import { StyleSheet } from "react-native";

export default StyleSheet.create({
  base: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#000000",
    color: "#000000",
  },
  initial: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#000000",
    color: "#000000",
  },
  home: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
    color: "#000000",
  },
  setting: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
    color: "#000000",
  },
  base: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
    color: "#000000",
  },
  play: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
    color: "#000000",
  },
  play2: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
    color: "#000000",
  },
  btn: {
    width: 80,
    height: 80,
  },
  btn_long: {
    width: 200,
    height: 60,
  },
  title: {
    width: 190,
    height: 120,
  },
  logo: {
    width: 280,
    height: 120,
  },
  loading_xx: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#225f6d",
  },
  background: {
    backgroundColor: "#88888844",
    height: "100%",
    width: "100%",
    position: "absolute",
    flex: 1,
  },
  loadingBackground: {
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    width: "100%",
    position: "absolute",
    flex: 1,
  },
  loading: {
    justifyContent: "center",
    alignItems: "center",
    height: 180,
    width: 180,
    position: "absolute",
    flex: 1,
  },
});
